### ISSUE TITLE
Cannot go full screen on tablets / mobile devices

### ISSUE THREAD

**Issue by justiceorjustus** [Tucsky/aggr#93]
Mobile browsers notoriously tend to not have a fullscreen button. I display aggr v3 on a tablet 24/7,  and I would love an on-page (or in the ... menu) fullscreen button so I can hide the browser address bar and see aggr v3 in all it's glory on the whole tablet.

**Comment by Tucsky** [comment]
Install the app from the browser to your home screen.
![Screenshot_20210920-092241](https://user-images.githubusercontent.com/5738336/133969012-7ff7f587-a923-4e4f-9b4a-a49da695199d.jpg)
![temp](https://user-images.githubusercontent.com/5738336/133969130-605c20fb-c917-41b6-b332-62b45d4360d5.jpg)
![Screenshot_20210920-092431](https://user-images.githubusercontent.com/5738336/133969142-1c380be9-f877-4a90-8bbc-054973047984.jpg)

The app then behave like a normal app, no address bar no nothing :)

**Comment by justiceorjustus** [comment]
> Install the app from the browser to your home screen.
> ![Screenshot_20210920-092241](https://user-images.githubusercontent.com/5738336/133969012-7ff7f587-a923-4e4f-9b4a-a49da695199d.jpg)
> ![temp](https://user-images.githubusercontent.com/5738336/133969130-605c20fb-c917-41b6-b332-62b45d4360d5.jpg)
> ![Screenshot_20210920-092431](https://user-images.githubusercontent.com/5738336/133969142-1c380be9-f877-4a90-8bbc-054973047984.jpg)
> 
> The app then behave like a normal app, no address bar no nothing :)

What browser are you using? I don't see the option on a Kindle Fire 10 through either Brave or Chrome...

**Comment by justiceorjustus** [comment]
Here's what the menu shows on the Fire 10
![20210920_100317](https://user-images.githubusercontent.com/27013322/134016079-88c5c446-b50c-4901-9865-4bec80821e9a.jpg)

**Comment by Tucsky** [comment]
Just installed brave to test and this appeared at the bottom of the page
<img src="https://user-images.githubusercontent.com/5738336/134017785-dc99637a-109b-45b4-913e-55f498dee321.jpg" width="250px" />

I have the "install" button on menu too...
<img src="https://user-images.githubusercontent.com/5738336/134017869-023f6f2b-9d5b-4742-8287-704d9a4da98f.jpg" width="250px" />


Could be cache issue ? Normally browser should download last version when I make an update but mobile browser sometime force using cache anyway, I implemented this install thing months ago tho...

You could to clear cache on brave (without clearing user data, idk if thats possible on Brave tbh) or this: export workspace, reset and re-import : 
- Download workspace (it's a .json with all the settings in it)
<img src="https://user-images.githubusercontent.com/5738336/134018595-cc627136-5680-4bb5-b418-5e97fbdf200b.jpg" width="250px" />

- Press reset button in the settings panel, confirm
<img src="https://user-images.githubusercontent.com/5738336/134019224-7768fa08-a15b-4f96-829a-93838eeace6d.jpg" width="250px" />


- Import back the workspace you just downloaded
<img src="https://user-images.githubusercontent.com/5738336/134019147-ab8ad61b-e1ca-4fab-9fc2-5938dfac59f7.jpg" width="250px" />

This should ensure you run the latest version which include the install button

**Comment by justiceorjustus** [comment]
Really weird... the popup you mentioned shows up on my Samsung Galaxy phone, but still not on the Fire 10 tablet after clearing cache. The "install app" is also there on my phone...

**Comment by justiceorjustus** [comment]
Is there a way that you can add a dedicated fullscreen button or I can buy and send you a Fire tablet? I'd be more than happy to since I've gotten much more than that in value out of aggr.

**Comment by justiceorjustus** [comment]
@Tucsky Thank you!!! Awesome!
